`new_sistema_cursos` 
  `codigocursos` int(11) NOT NULL,
  `nomecurso` varchar(50) DEFAULT NULL,
  `matriz` int(11) DEFAULT NULL,
  `heroSC` text,
  `beneficiosSC` text,
  `sobreSC` text,
  `ctaSC` text,
  `codpagina` int(11) DEFAULT NULL,
  `codpagesadminsc` int(11) DEFAULT '0',
  `codsessao` int(11) DEFAULT NULL,
  `cargahoraria` int(11) DEFAULT '2',
  `horasemanalsc` int(11) DEFAULT NULL,
  `horaporaulasc` int(11) DEFAULT NULL,
  `bgcolor` varchar(10) DEFAULT '#cccccc',
  `anualsc` int(11) DEFAULT NULL,
  `mensalsc` int(11) DEFAULT NULL,
  `capa` int(11) DEFAULT '0',
  `termos` text,
  `horadem` time DEFAULT NULL,
  `horaparam` time DEFAULT NULL,
  `horadet` time DEFAULT NULL,
  `horaparat` time DEFAULT NULL,
  `horaden` time DEFAULT NULL,
  `horaparan` time DEFAULT NULL,
  `lead` varchar(300) DEFAULT NULL,
  `detalhes` text,
  `sobreocurso` varchar(300) DEFAULT NULL,
  `carousel_titulo` varchar(200) DEFAULT NULL,
  `carousel_subtitulo` varchar(200) DEFAULT NULL,
  `carousel_descricao` varchar(200) DEFAULT NULL,
  `carousel_devalor` varchar(200) DEFAULT NULL,
  `diretorio` varchar(150) DEFAULT NULL,
  `chaveturmasc` varchar(50) DEFAULT NULL,
  `valorsc` float(9,2) DEFAULT '0.00',
  `pagseguro` text,
  `linkpix` text,
  `linkexterno` varchar(300) DEFAULT NULL,
  `chavepix` text,
  `valorassinante` float(5,2) DEFAULT '0.00',
  `valordesconto` float(5,2) DEFAULT '0.00',
  `pixsc` text,
  `cargahorariasc` int(11) DEFAULT '4',
  `horariodesc` varchar(10) DEFAULT NULL,
  `horarioparasc` varchar(10) DEFAULT NULL,
  `datainiciosc` date DEFAULT NULL,
  `segsc` int(11) NOT NULL DEFAULT '0',
  `tersc` int(11) NOT NULL DEFAULT '0',
  `quasc` int(11) NOT NULL DEFAULT '0',
  `quisc` int(11) NOT NULL DEFAULT '0',
  `sexsc` int(11) NOT NULL DEFAULT '0',
  `sabsc` int(11) NOT NULL DEFAULT '0',
  `cnpj_cat` varchar(20) DEFAULT NULL,
  `youtubeurl` varchar(300) DEFAULT NULL,
  `link_site` varchar(200) DEFAULT NULL,
  `tagssc` varchar(250) DEFAULT NULL,
  `inscricaoonline` int(11) DEFAULT '0',
  `pasta` varchar(30) DEFAULT NULL,
  `mapa` text,
  `descricaosc` text,
  `descricaovendasc` text,
  `ordemsc` int(11) DEFAULT '1',
  `textosc` text,
  `visivelsc` int(11) DEFAULT '0',
  `externosc` int(11) DEFAULT '0',
  `lixeirasc` int(11) DEFAULT '0',
  `onlinesc` int(11) DEFAULT '0',
  `visivelhomesc` int(11) DEFAULT '0',
  `comercialsc` int(11) DEFAULT '0',
  `institucionalsc` int(11) DEFAULT '0',
  `datasc` date DEFAULT NULL,
  `horasc` time DEFAULT NULL