`new_sistema_cursos_turmas`
  `codigoturma` int(11) NOT NULL,
  `codcursost` int(11) DEFAULT NULL, 
  `ordemct` int(11) DEFAULT '1',
  `nometurma` varchar(250) DEFAULT NULL,
    `nomeprofessor` varchar(200) NOT NULL,
   `texto` text, 
`linkwhatsapp` varchar(100) DEFAULT '#',
  `datainiciost` date DEFAULT NULL, 
  `datafimst` date DEFAULT NULL, 
  `horainiciost` time DEFAULT NULL, 
  `horafimst` varchar(5) DEFAULT NULL,
  `chave` varchar(100) DEFAULT NULL,
  `datast` date DEFAULT NULL,
  `horast` time DEFAULT NULL,
  `ano_turma` int(4) DEFAULT NULL,
  
   `visivelst` int(11) DEFAULT '0',
 `comercialt` int(11) DEFAULT '0',
  `institucional` int(11) DEFAULT '0',

  `lead` varchar(300) DEFAULT NULL,
  `detalhes` text,
  `sobreocurso` varchar(300) DEFAULT NULL,


  `tipocurso` int(11) DEFAULT NULL,
  `bgcolor_cs` varchar(10) DEFAULT '#cccccc',
  `cargahorariasct` int(11) DEFAULT NULL,
  `horasaulast` int(11) DEFAULT NULL,
  `tagst` varchar(250) DEFAULT NULL,
  `youtubesct` varchar(250) DEFAULT NULL,
 
  `previa` text,

  `valorCursoPeriodo` decimal(9,2) DEFAULT NULL,
  `chavepixCursoPeriodo` varchar(300) DEFAULT NULL,
  `LinkCartaoCursoPeriodo` varchar(300) NOT NULL,
  `linkpix` varchar(300) DEFAULT '0',
  `chavepix` text,
  `valoranual` decimal(9,2) DEFAULT NULL,
  `valorvendavitalicia` float(9,2) DEFAULT '0.00',
  `linkpixvitalicia` float(9,2) DEFAULT NULL,
  `chavepixvitalicia` text,
  `imgqrcodecurso` varchar(300) DEFAULT NULL,
  `imgqrcodeanual` varchar(300) DEFAULT NULL,
  `imgqrcodevitalicio` varchar(300) DEFAULT NULL,
  `linkpagseguro` text,
  `linkpagsegurovitalicia` text,
  `linkmercadopago` text,
  `linkmercadopagovitalicio` text,
  `codadmin` int(11) DEFAULT '1',
  `valorhoraaula` decimal(9,2) DEFAULT NULL,
  `dataevento` date DEFAULT NULL,

  `coduser` int(11) DEFAULT '1',
  `codsessao` int(11) DEFAULT NULL,
  `codturno` int(11) DEFAULT '1',
  `codpageadminst` int(11) DEFAULT NULL,
  `codcurso` int(11) DEFAULT '0',
  `codpagesadmin` int(11) DEFAULT NULL,
  `codcursos` int(11) DEFAULT NULL,
  `programacao` datetime DEFAULT NULL,
  `codpagina` int(11) DEFAULT '0',
  `codtema` int(11) DEFAULT NULL,
  `dias` varchar(50) DEFAULT NULL,
  `valorcusto` float(10,2) DEFAULT NULL,
  `valorvenda` float(10,2) DEFAULT NULL,
  `chavepixvalorvenda` text,
  `link` varchar(70) DEFAULT '#',
  `autor` varchar(250) DEFAULT NULL,
  `linkconteudo` varchar(250) DEFAULT 'http://#',
  `tag` varchar(30) DEFAULT NULL,
  `pasta` varchar(50) DEFAULT NULL,
  `data` date DEFAULT NULL,
  `hora` time DEFAULT NULL,
  `datast` date DEFAULT NULL,
  `horast` time DEFAULT NULL,
  `ano_turma` int(4) DEFAULT NULL,
  `dataatualizacao` date DEFAULT NULL,
  `horaatualizacao` time DEFAULT NULL,
  `comercial_stc` int(11) DEFAULT '0',

 
  `visiveltube` int(11) DEFAULT NULL,
  `andamento` int(11) DEFAULT '0',
  `publico` int(11) DEFAULT '0',
 
  `destaque` int(11) DEFAULT '0'